export const INCREMENT = 'INCREMENT';

export const DECREMENT = 'DECREMENT';

export const ADD_BOOK_TO_SHOPPING_CART = 'ADD_BOOK_TO_SHOPPING_CART';

export const DELETE_BOOK_FROM_SHOPPING_CART = 'DELETE_BOOK_FROM_SHOPPING_CART';

export const DELETE_ALL_FROM_SHOPPING_CART = 'DELETE_ALL_FROM_SHOPPING_CART';

export const DELETE_MANY_CART_ITEMS = 'DELETE_MANY_CART_ITEMS';

export const CHANGE_CART_ITEM_AMOUNT = 'CHANGE_CART_ITEM_AMOUNT';

export const USER_LOGIN = 'USER_LOGIN';

export const USER_LOGOUT = 'USER_LOGOUT';